//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordLabel.Web.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminApplicationLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminApplicationLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecordLabel.Web.Localization.AdminApplicationLocalization", typeof(AdminApplicationLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an Image....
        /// </summary>
        public static string ChooseAnImage {
            get {
                return ResourceManager.GetString("ChooseAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Image.
        /// </summary>
        public static string Edit_AddImage {
            get {
                return ResourceManager.GetString("Edit_AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Edit_AddNew {
            get {
                return ResourceManager.GetString("Edit_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Reference.
        /// </summary>
        public static string Edit_AddReference {
            get {
                return ResourceManager.GetString("Edit_AddReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Track.
        /// </summary>
        public static string Edit_AddTrack {
            get {
                return ResourceManager.GetString("Edit_AddTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Artists.
        /// </summary>
        public static string Edit_BackToArtists {
            get {
                return ResourceManager.GetString("Edit_BackToArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Attributes.
        /// </summary>
        public static string Edit_BackToAttributes {
            get {
                return ResourceManager.GetString("Edit_BackToAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Media Types.
        /// </summary>
        public static string Edit_BackToMediaTypes {
            get {
                return ResourceManager.GetString("Edit_BackToMediaTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit References.
        /// </summary>
        public static string Edit_EditReferences {
            get {
                return ResourceManager.GetString("Edit_EditReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Tracklist.
        /// </summary>
        public static string Edit_EditTracklist {
            get {
                return ResourceManager.GetString("Edit_EditTracklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, this release will be in the Other Versions list for other releases to be used as a primary version.
        /// </summary>
        public static string Edit_MasterVersion_Info {
            get {
                return ResourceManager.GetString("Edit_MasterVersion_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option cannot be changed because this release serves as a primary version for other releases. To be able to change this value, you need to remove this association from other releases referencing this one.
        /// </summary>
        public static string Edit_MasterVersion_Info_CantChangeOption {
            get {
                return ResourceManager.GetString("Edit_MasterVersion_Info_CantChangeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay Signed In.
        /// </summary>
        public static string Login_RememberMe {
            get {
                return ResourceManager.GetString("Login_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string Login_UserName {
            get {
                return ResourceManager.GetString("Login_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Modal_OK {
            get {
                return ResourceManager.GetString("Modal_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        public static string NavSection_Artists {
            get {
                return ResourceManager.GetString("NavSection_Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string NavSection_Attributes {
            get {
                return ResourceManager.GetString("NavSection_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string NavSection_LogOut {
            get {
                return ResourceManager.GetString("NavSection_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediaTypes.
        /// </summary>
        public static string NavSection_MediaTypes {
            get {
                return ResourceManager.GetString("NavSection_MediaTypes", resourceCulture);
            }
        }
    }
}
