//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordLabel.Content.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContentLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecordLabel.Content.Localization.ContentLocalization", typeof(ContentLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Article_Author {
            get {
                return ResourceManager.GetString("Article_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Article_Date {
            get {
                return ResourceManager.GetString("Article_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Article_Title {
            get {
                return ResourceManager.GetString("Article_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Article_Type {
            get {
                return ResourceManager.GetString("Article_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string ArticleType_Article {
            get {
                return ResourceManager.GetString("ArticleType_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string ArticleType_News {
            get {
                return ResourceManager.GetString("ArticleType_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Artist_Description {
            get {
                return ResourceManager.GetString("Artist_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Artist_Name {
            get {
                return ResourceManager.GetString("Artist_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Base_Text {
            get {
                return ResourceManager.GetString("Base_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue Number.
        /// </summary>
        public static string CatalogueNumber {
            get {
                return ResourceManager.GetString("CatalogueNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Recorded.
        /// </summary>
        public static string DateRecorded {
            get {
                return ResourceManager.GetString("DateRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Master Version.
        /// </summary>
        public static string IsMasterVersion {
            get {
                return ResourceManager.GetString("IsMasterVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics By.
        /// </summary>
        public static string LyricsBy {
            get {
                return ResourceManager.GetString("LyricsBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Metadata_Name {
            get {
                return ResourceManager.GetString("Metadata_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music By.
        /// </summary>
        public static string MusicBy {
            get {
                return ResourceManager.GetString("MusicBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playtime.
        /// </summary>
        public static string Playtime {
            get {
                return ResourceManager.GetString("Playtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        public static string PrintStatus {
            get {
                return ResourceManager.GetString("PrintStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string PrintStatus_InPrint {
            get {
                return ResourceManager.GetString("PrintStatus_InPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        public static string PrintStatus_OutOfPrint {
            get {
                return ResourceManager.GetString("PrintStatus_OutOfPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display As.
        /// </summary>
        public static string Reference_DisplayAs {
            get {
                return ResourceManager.GetString("Reference_DisplayAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Reference_Target {
            get {
                return ResourceManager.GetString("Reference_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Reference_Type {
            get {
                return ResourceManager.GetString("Reference_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        public static string References {
            get {
                return ResourceManager.GetString("References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string ReferenceType_File {
            get {
                return ResourceManager.GetString("ReferenceType_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Video.
        /// </summary>
        public static string ReferenceType_OtherVideo {
            get {
                return ResourceManager.GetString("ReferenceType_OtherVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string ReferenceType_Website {
            get {
                return ResourceManager.GetString("ReferenceType_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube.
        /// </summary>
        public static string ReferenceType_Youtube {
            get {
                return ResourceManager.GetString("ReferenceType_Youtube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string Release_Artist {
            get {
                return ResourceManager.GetString("Release_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string Release_Date {
            get {
                return ResourceManager.GetString("Release_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Release_Description {
            get {
                return ResourceManager.GetString("Release_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Versions.
        /// </summary>
        public static string Release_OtherVersions {
            get {
                return ResourceManager.GetString("Release_OtherVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle.
        /// </summary>
        public static string Release_Subtitle {
            get {
                return ResourceManager.GetString("Release_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Releases.
        /// </summary>
        public static string Releases {
            get {
                return ResourceManager.GetString("Releases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracklist.
        /// </summary>
        public static string Tracklist {
            get {
                return ResourceManager.GetString("Tracklist", resourceCulture);
            }
        }
    }
}
